"""
Stage Service for managing workflow stages.

Handles stage transitions, progress tracking, and stage-specific logic.
"""

import logging
from datetime import datetime
from typing import Dict, Any, List

logger = logging.getLogger(__name__)


class StageService:
    """Service for managing workflow stages and transitions."""
    
    STAGE_PROGRESS_MAP = {
        "ideation": 5,
        "research": 15,
        "character_development": 25,
        "world_building": 40,
        "plot_development": 55,
        "chapter_planning": 70,
        # Chapter writing stages are calculated dynamically
        "manuscript_assembly": 95,
        "completed": 100
    }
    
    def __init__(self, project_id: str, central_hub):
        self.project_id = project_id
        self.central_hub = central_hub
        self.current_stage = None
        self.completed_stages = []
        self.last_progress_time = None
        
    def update_stage(self, stage: str) -> None:
        """Update the current stage."""
        self.current_stage = stage
        self.last_progress_time = datetime.now().isoformat()
        
        # Calculate progress based on stage
        progress = self._calculate_progress(stage)
        self._update_progress(progress)
        
        logger.info(f"Project {self.project_id} moved to stage: {stage} (progress: {progress}%)")
    
    def complete_stage(self, stage: str) -> None:
        """Mark a stage as completed."""
        if stage not in self.completed_stages:
            self.completed_stages.append(stage)
        
        # Update status
        status_data = {
            "status": "running",
            "progress": self._calculate_progress(self.current_stage),
            "current_stage": self.current_stage,
            "completed_stages": self.completed_stages,
            "last_update": datetime.now().isoformat()
        }
        self.central_hub.update_project_status(status_data)
        
        logger.info(f"Project {self.project_id} completed stage: {stage}")
    
    def _calculate_progress(self, stage: str) -> int:
        """Calculate progress based on stage."""
        # For chapter writing stages, interpolate between 70 and 95
        if stage.startswith("writing_chapter_"):
            try:
                chapter_num = int(stage.split("_")[-1])
                total_chapters = self._get_total_chapters()
                
                if total_chapters == 0:
                    total_chapters = 10  # Default
                
                # Calculate progress (70% base + up to 25% for chapters)
                chapter_progress = int(70 + ((chapter_num - 1) / total_chapters) * 25)
                return min(95, chapter_progress)
            except:
                return 70
        else:
            return self.STAGE_PROGRESS_MAP.get(stage, self._get_current_progress())
    
    def _get_total_chapters(self) -> int:
        """Get total number of chapters from chapter plan."""
        try:
            from memory.dynamic_memory import DynamicMemory
            from models.openai_client import get_openai_client
            import json
            
            # Initialize memory
            openai_client = get_openai_client()
            embedding_function = lambda text: openai_client.get_embeddings(text, model="text-embedding-3-large")
            memory = DynamicMemory(self.project_id, embedding_function)
            
            chapter_docs = memory.query_memory("type:chapter_plan", agent_name="chapter_planner_agent")
            if chapter_docs:
                chapter_plan = json.loads(chapter_docs[0].get("text", "{}"))
                return len(chapter_plan.get("chapters", []))
        except:
            pass
        return 0
    
    def _get_current_progress(self) -> int:
        """Get current progress from central hub."""
        status = self.central_hub.get_project_status()
        return status.get("progress", 0)
    
    def _update_progress(self, progress: int) -> None:
        """Update the progress percentage."""
        status_data = {
            "status": "running",
            "progress": progress,
            "current_stage": self.current_stage,
            "completed_stages": self.completed_stages,
            "last_update": datetime.now().isoformat()
        }
        self.central_hub.update_project_status(status_data)
    
    def get_stage_data(self, stage: str) -> Dict[str, Any]:
        """Get data generated by a specific stage."""
        from memory.dynamic_memory import DynamicMemory
        from models.openai_client import get_openai_client
        import json
        
        try:
            # Initialize memory
            openai_client = get_openai_client()
            embedding_function = lambda text: openai_client.get_embeddings(text, model="text-embedding-3-large")
            memory = DynamicMemory(self.project_id, embedding_function)
            
            stage_mapping = {
                "ideation": ("type:selected_idea", "ideation_agent"),
                "character": ("type:characters", "character_agent"),
                "world": ("type:world", "world_building_agent"),
                "research": ("type:research", "research_agent"),
                "plot": ("type:plot", "plot_agent"),
                "chapter_plan": ("type:chapter_plan", "chapter_planner_agent")
            }
            
            if stage in stage_mapping:
                query, agent = stage_mapping[stage]
                data = memory.query_memory(query, agent_name=agent)
                if data:
                    return json.loads(data[0]["text"])
        except Exception as e:
            logger.error(f"Error getting stage data for {stage}: {str(e)}")
        
        return None
    
    def visualize_workflow(self) -> Dict[str, Any]:
        """Get a visualization of the workflow state."""
        nodes = [
            {"id": "ideation", "label": "Ideation", "status": "completed" if "ideation" in self.completed_stages else "pending"},
            {"id": "research", "label": "Research", "status": "completed" if "research" in self.completed_stages else "pending"},
            {"id": "character_development", "label": "Character Development", "status": "completed" if "character_development" in self.completed_stages else "pending"},
            {"id": "world_building", "label": "World Building", "status": "completed" if "world_building" in self.completed_stages else "pending"},
            {"id": "plot_development", "label": "Plot Development", "status": "completed" if "plot_development" in self.completed_stages else "pending"},
            {"id": "chapter_planning", "label": "Chapter Planning", "status": "completed" if "chapter_planning" in self.completed_stages else "pending"},
            {"id": "chapter_writing", "label": "Chapter Writing", "status": "completed" if any(s.startswith("writing_chapter_") for s in self.completed_stages) else "pending"},
            {"id": "manuscript_assembly", "label": "Manuscript Assembly", "status": "completed" if "manuscript_assembly" in self.completed_stages else "pending"}
        ]
        
        # Mark current stage
        for node in nodes:
            if node["id"] == self.current_stage:
                node["status"] = "current"
        
        # Define edges
        edges = [
            {"source": "ideation", "target": "research", "label": "Follows"},
            {"source": "research", "target": "character_development", "label": "Follows"},
            {"source": "character_development", "target": "world_building", "label": "Follows"},
            {"source": "world_building", "target": "plot_development", "label": "Follows"},
            {"source": "plot_development", "target": "chapter_planning", "label": "Follows"},
            {"source": "chapter_planning", "target": "chapter_writing", "label": "Follows"},
            {"source": "chapter_writing", "target": "manuscript_assembly", "label": "Follows"}
        ]
        
        return {
            "nodes": nodes,
            "edges": edges,
            "progress": self._get_current_progress(),
            "current_stage": self.current_stage,
            "completed_stages": self.completed_stages
        }
